### ISSUE TITLE
Content in middle panel and right panel disappears when the same topic is clicked

### ISSUE THREAD

**Issue by shuson** [cnodejs/cnodejs-reader#1]
How to reproduce:
1. open home page: http://r.nodejs-china.org/
2. click a topic on the left panel, the middle and right panel is filled with content
3. click the same topic again, content in middle and right panel disappears.

**Comment by alsotang** [comment]
试了一下，我这也重现了

2015-10-28 10:21 GMT+08:00 Shusen Wang notifications@github.com:

**Comment by tiye** [comment]
There's still bugs in router, which is [router-view](https://github.com/teambition/router-view), especially in Hash mode. I need to fix that later.

**Comment by alsotang** [comment]
牛人啊，组件都是自己写的

2015-10-28 12:33 GMT+08:00 题叶 notifications@github.com:

**Comment by tiye** [comment]
前端困难的事情, 一个是多种多样的设备的坑, 一个制造开发方案比如 Webpack, React, Vue.
我这只是个百来行的小组件, 而且没有解决掉所有细节... 没什么高大上的技术~

**Comment by tiye** [comment]
should work now, please check

**Comment by alsotang** [comment]
嗯嗯好了。
我以为再次点击会有类似刷新的效果，现在看来是直接忽略点击事件了。。

2015-11-04 1:02 GMT+08:00 题叶 notifications@github.com:

**Comment by tiye** [comment]
刷新需要通过 `refresh` 按钮来做, 是整个话题列表刷新的.

**Comment by alsotang** [comment]
点击同一话题的时候，可以单个 topic 的刷新，而非整个话题列表刷新啊

2015-11-04 13:24 GMT+08:00 题叶 notifications@github.com:

**Comment by tiye** [comment]
架构设计的时候没有从这一点考虑的..  而是尽量用本地的缓存数据, 加快渲染.
