### ISSUE TITLE
布局显示有问题

### ISSUE THREAD

**Issue by TakWolf** [cnodejs/cnodejs-reader#3]
![image](https://cloud.githubusercontent.com/assets/6064962/14581840/7e55bfd4-0429-11e6-8996-ea43f7d80eb3.png)

右侧的文章内容基本看不到了

**Comment by tiye** [comment]
呃, 我都忘了有这个情况了... 其实是个横向的滚动条, Mac 里触摸板可以直接横向的, Windows 呃...

**Comment by TakWolf** [comment]
@jiyinyiyong  
我去看了一下源代码，有点惊讶到了。
高大上啊，有点看不懂啊。。

**Comment by tiye** [comment]
@TakWolf 定制过语法的 JavaScript ... http://script.cirru.org/
